version: '3.8'

services:
  rbtc-bot:
    build: .
    container_name: rbtc-telegram-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # 지갑 데이터와 로그를 호스트와 공유
      - ./wallets.json:/app/wallets.json
      - ./logs:/app/logs
      - ./tx_bot.log:/app/tx_bot.log
    environment:
      - TZ=Asia/Seoul
    networks:
      - bot-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('https://api.telegram.org')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  bot-network:
    driver: bridge